import { NormalizedPosition } from '../brokers/types';

/**
 * Deterministic test fixtures for Phase 4 P&L calculations.
 */

export const FIXTURE_LONG_FUT_PROFIT: NormalizedPosition = {
  instrumentToken: 200001,
  exchange: 'NFO',
  tradingsymbol: 'TEST_LONG_FUT_PROFIT',
  segment: 'NFO-FUT',
  instrumentType: 'FUTURE',
  product: 'NRML',
  quantity: 50,
  averagePrice: 100,
  lastPrice: 110,
  dayBuyQuantity: 50,
  dayBuyValue: 5000,
  daySellQuantity: 0,
  daySellValue: 0,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_LONG_FUT_LOSS: NormalizedPosition = {
  instrumentToken: 200002,
  exchange: 'NFO',
  tradingsymbol: 'TEST_LONG_FUT_LOSS',
  segment: 'NFO-FUT',
  instrumentType: 'FUTURE',
  product: 'NRML',
  quantity: 50,
  averagePrice: 100,
  lastPrice: 90,
  dayBuyQuantity: 50,
  dayBuyValue: 5000,
  daySellQuantity: 0,
  daySellValue: 0,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_SHORT_FUT_PROFIT: NormalizedPosition = {
  instrumentToken: 200003,
  exchange: 'NFO',
  tradingsymbol: 'TEST_SHORT_FUT_PROFIT',
  segment: 'NFO-FUT',
  instrumentType: 'FUTURE',
  product: 'NRML',
  quantity: -50,
  averagePrice: 100,
  lastPrice: 90,
  dayBuyQuantity: 0,
  dayBuyValue: 0,
  daySellQuantity: 50,
  daySellValue: 5000,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_SHORT_FUT_LOSS: NormalizedPosition = {
  instrumentToken: 200004,
  exchange: 'NFO',
  tradingsymbol: 'TEST_SHORT_FUT_LOSS',
  segment: 'NFO-FUT',
  instrumentType: 'FUTURE',
  product: 'NRML',
  quantity: -50,
  averagePrice: 100,
  lastPrice: 110,
  dayBuyQuantity: 0,
  dayBuyValue: 0,
  daySellQuantity: 50,
  daySellValue: 5000,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_LONG_OPT_PROFIT: NormalizedPosition = {
  instrumentToken: 200005,
  exchange: 'NFO',
  tradingsymbol: 'TEST_LONG_OPT_PROFIT',
  segment: 'NFO-OPT',
  instrumentType: 'OPTION',
  product: 'NRML',
  quantity: 25,
  averagePrice: 80,
  lastPrice: 120,
  dayBuyQuantity: 25,
  dayBuyValue: 2000,
  daySellQuantity: 0,
  daySellValue: 0,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_SHORT_OPT_PROFIT: NormalizedPosition = {
  instrumentToken: 200006,
  exchange: 'NFO',
  tradingsymbol: 'TEST_SHORT_OPT_PROFIT',
  segment: 'NFO-OPT',
  instrumentType: 'OPTION',
  product: 'NRML',
  quantity: -25,
  averagePrice: 120,
  lastPrice: 80,
  dayBuyQuantity: 0,
  dayBuyValue: 0,
  daySellQuantity: 25,
  daySellValue: 3000,
  realisedPnl: 0,
  unrealisedPnl: 0,
  totalPnl: 0,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_ZERO_QTY_CLOSED: NormalizedPosition = {
  instrumentToken: 200007,
  exchange: 'NFO',
  tradingsymbol: 'TEST_CLOSED_INTRA',
  segment: 'NFO-FUT',
  instrumentType: 'FUTURE',
  product: 'MIS',
  quantity: 0,
  averagePrice: 52100,
  lastPrice: 52180,
  dayBuyQuantity: 30,
  dayBuyValue: 1563000,
  daySellQuantity: 30,
  daySellValue: 1564200,
  realisedPnl: 1200,
  unrealisedPnl: 0,
  totalPnl: 1200,
  isFno: true,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_EQUITY_WITH_PNL: NormalizedPosition = {
  instrumentToken: 200008,
  exchange: 'NSE',
  tradingsymbol: 'RELIANCE',
  segment: 'NSE-EQ',
  instrumentType: 'EQUITY',
  product: 'CNC',
  quantity: 100,
  averagePrice: 2950,
  lastPrice: 2985,
  dayBuyQuantity: 100,
  dayBuyValue: 295000,
  daySellQuantity: 0,
  daySellValue: 0,
  realisedPnl: 500,
  unrealisedPnl: 3500,
  totalPnl: 4000,
  isFno: false,
  dataSource: 'MOCK_DATA',
};

export const FIXTURE_EQUITY_MISLEADING_SYMBOL: NormalizedPosition = {
  instrumentToken: 200009,
  exchange: 'NSE',
  tradingsymbol: 'TATACOFFEEFUT',
  segment: 'NSE-EQ',
  instrumentType: 'EQUITY',
  product: 'CNC',
  quantity: 50,
  averagePrice: 300,
  lastPrice: 320,
  dayBuyQuantity: 50,
  dayBuyValue: 15000,
  daySellQuantity: 0,
  daySellValue: 0,
  realisedPnl: 0,
  unrealisedPnl: 1000,
  totalPnl: 1000,
  isFno: false,
  dataSource: 'MOCK_DATA',
};
